[connections.gsheets]
type = "gsheets"
spreadsheet = "https://docs.google.com/spreadsheets/d/1jb6KXwd7UdVijMr9zuqlf5HJqZvKsuaMiojhbBXPYB4/edit?usp=sharing"

[connections.gsheets.credentials]
type = "service_account"
project_id = "friendly-ward-476112-q8"
private_key_id = "6e031ddcbff6f40719ddffe0e835857e282e8eec"
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDoqynFcbHZwMKO\nbds8g5Mn94cEog2k3gOU+e9IdXjjJppZnvaTr5c7HAYxXinqg412SNOtM2zT8zHs\nCNCR3DvNPfM/ElrQ10yiIS3rtp2bU/ROBR5kvMmcXAAvsUiz7GRfwaErojPMm0a3\nazzPkbrB4svrI0l+zOW7fJZFcdxulTOfMojmki34Xiy1o7a4uua4HTc8UXYmqS0H\nuHR7YV5rX6V/mp9Ee9aiyzUqbnXYZUxTqZkCdWsrJMYDJXzqSg4hjMXtv8dT/pBL\naRhDl6A7of3HoguZHOGSCT9u0FpcSUria+14381eqNF0XbQ+vfM6w5Dnxpe0nCDj\n3lREf+DfAgMBAAECggEAHprf5GrvhsHbqw85oXIlRJfuGLvq/jQoqyCyoF4OHW28\ngUFvFJTVAx936RKGgk9KUl7Ys+sUdk+CfOvZPkvb9Jl2NREIWnmXnlQC+FiNzsVy\nWLjvpeH3cIE257nIOHKbRBqc8A0RXJP9mgREfCv33FJ67wk157SyxhYTUOXd+xBB\nARgq3r0W21aCb//VzgbfMlhAIGrmIddIHF21qKP6j4ATnQmr2U/jGPPj/PkCt9pT\nnXAWE46TMRtsd3vBqh5gvw1PEr6IIGpFzC6ll1MWlOH05TyR5nkdlZTYaUR3Ppee\nppVTGZvOCT5JA7jKAQ4A59sLUNDSnfgGngdbcpddgQKBgQD5F8bnPEtjPgK3U5ma\nCmhWMiQmsagj3j1H/zYVbqK9kHjAIziuSAYsiDLa2MqvGDNZRhXsmeQWj0wbZ8Ik\nhBM9q1fyh/MAyi3J/pR2umV0pd+vaHUf/PqWB3FrcS3X2tpwlfVbkpy9tiTXYqlj\nmfPRgOO+/qB10XBf+rM01PIhfwKBgQDvHsvJ2MMSdgQFKAFY/OXmY1gJ2Z9d5tuI\nlwQkdXvL2cY8nUy2RwtSD00TM2tIp8YRyRtHusRTfWEzrUxOgRkDatdMmH4xkxGf\n4TLkoU8Os5PjSriJj+OJIVFPXV5kPlqGA+L9ZC+hdGY2tVXoz6GCOQO8u1BbdFiJ\noog5xI8woQKBgQDQKne2LSRPZrY8YOgf3Iy/ZB3kHFoIx6Rs87JODOyCASd4Yrbu\npxBJzPS7Aau40j+vXqvZ0+3SkKSoznhnrdyqj/PqooSI522GvnNyGWnKJwkdfO1M\n80yzbrrxcF9AYgxlRF0MzySgQoTdXv1yWGlzbwRlTEPq0kHYZBm5kDBdnwKBgQDC\n5w0gRwgpgfwg38zJZclWEl9uF+3oMgV6vezocsInFCiau3QNlrbJeiNOpTirDeVK\nFeugecEQdD/ISVbLHjrvKCS5EAq8Ca3x7TL4W+r+hqziNMNZjOjfm0KVN/t6JcDP\nP1fDRef059Vwfjm5+5Mfe61qJhuHj7ui49G5lFdKQQKBgE9WmVCug7pOxS+AcgcQ\nE3I4nHd4TYybWbBIg5O7xk96Z44nIi9/K0xuKGRm4XO6rPJom+Go87UUAYw3/f6E\nb84+vCMOfz6rzKM7wMMcTwa+7Zuy+TSdFcIQCgDqt2L8lePuxzmbvDGl+EP/bBkU\nVyhX6C3GChKSk3m0ZQMJjp6O\n-----END PRIVATE KEY-----\n"
client_email = "streamlit-history@friendly-ward-476112-q8.iam.gserviceaccount.com"
client_id = "108670586033992861878"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-history%40friendly-ward-476112-q8.iam.gserviceaccount.com"

#[connections.supabase_db]
#dialect = "postgresql"
#host = "db.upfywhhrpkgwjahgiygf.supabase.co" 
#port = 5432
#database = "postgres"
#username = "postgres"
#password = "CandraSaki28"

ADMIN_PASSWORD = "1234"